# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/design_1/ip/design_1_batch_align2D_0_9/design_1_batch_align2D_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_batch_align2D_0_9 || ORIG_REF_NAME==design_1_batch_align2D_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_7/design_1_zynq_ultra_ps_e_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_7 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_13/design_1_xbar_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_13 || ORIG_REF_NAME==design_1_xbar_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps8_0_axi_periph_7/design_1_ps8_0_axi_periph_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps8_0_axi_periph_7 || ORIG_REF_NAME==design_1_ps8_0_axi_periph_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_99M_7/design_1_rst_ps8_0_99M_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_99M_7 || ORIG_REF_NAME==design_1_rst_ps8_0_99M_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_5/design_1_axi_smc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_5 || ORIG_REF_NAME==design_1_axi_smc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
