-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (lin64) Build 2405991 Thu Dec  6 23:36:41 MST 2018
-- Date        : Sun Jan  5 21:04:02 2020
-- Host        : compute.eees.dei.unibo.it running 64-bit CentOS Linux release 7.6.1810 (Core)
-- Command     : write_vhdl -force -mode synth_stub
--               /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_region_0_1/design_1_batch_align2D_region_0_1_stub.vhdl
-- Design      : design_1_batch_align2D_region_0_1
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu9eg-ffvb1156-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_batch_align2D_region_0_1 is
  Port ( 
    s_axi_ctrl_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_ctrl_AWVALID : in STD_LOGIC;
    s_axi_ctrl_AWREADY : out STD_LOGIC;
    s_axi_ctrl_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_ctrl_WVALID : in STD_LOGIC;
    s_axi_ctrl_WREADY : out STD_LOGIC;
    s_axi_ctrl_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_BVALID : out STD_LOGIC;
    s_axi_ctrl_BREADY : in STD_LOGIC;
    s_axi_ctrl_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_ctrl_ARVALID : in STD_LOGIC;
    s_axi_ctrl_ARREADY : out STD_LOGIC;
    s_axi_ctrl_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_RVALID : out STD_LOGIC;
    s_axi_ctrl_RREADY : in STD_LOGIC;
    s_axi_param_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_param_AWVALID : in STD_LOGIC;
    s_axi_param_AWREADY : out STD_LOGIC;
    s_axi_param_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_param_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_param_WVALID : in STD_LOGIC;
    s_axi_param_WREADY : out STD_LOGIC;
    s_axi_param_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_param_BVALID : out STD_LOGIC;
    s_axi_param_BREADY : in STD_LOGIC;
    s_axi_param_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_param_ARVALID : in STD_LOGIC;
    s_axi_param_ARREADY : out STD_LOGIC;
    s_axi_param_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_param_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_param_RVALID : out STD_LOGIC;
    s_axi_param_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_my_region_data_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_data_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_region_data_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_data_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_data_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_AWVALID : out STD_LOGIC;
    m_axi_my_region_data_AWREADY : in STD_LOGIC;
    m_axi_my_region_data_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_data_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_WLAST : out STD_LOGIC;
    m_axi_my_region_data_WVALID : out STD_LOGIC;
    m_axi_my_region_data_WREADY : in STD_LOGIC;
    m_axi_my_region_data_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_BVALID : in STD_LOGIC;
    m_axi_my_region_data_BREADY : out STD_LOGIC;
    m_axi_my_region_data_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_data_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_region_data_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_data_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_data_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_data_ARVALID : out STD_LOGIC;
    m_axi_my_region_data_ARREADY : in STD_LOGIC;
    m_axi_my_region_data_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_data_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_data_RLAST : in STD_LOGIC;
    m_axi_my_region_data_RVALID : in STD_LOGIC;
    m_axi_my_region_data_RREADY : out STD_LOGIC;
    m_axi_my_region_fcoord_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_fcoord_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_region_fcoord_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_fcoord_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_fcoord_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_AWVALID : out STD_LOGIC;
    m_axi_my_region_fcoord_AWREADY : in STD_LOGIC;
    m_axi_my_region_fcoord_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_fcoord_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_WLAST : out STD_LOGIC;
    m_axi_my_region_fcoord_WVALID : out STD_LOGIC;
    m_axi_my_region_fcoord_WREADY : in STD_LOGIC;
    m_axi_my_region_fcoord_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_BVALID : in STD_LOGIC;
    m_axi_my_region_fcoord_BREADY : out STD_LOGIC;
    m_axi_my_region_fcoord_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_fcoord_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_region_fcoord_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_fcoord_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_region_fcoord_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_region_fcoord_ARVALID : out STD_LOGIC;
    m_axi_my_region_fcoord_ARREADY : in STD_LOGIC;
    m_axi_my_region_fcoord_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_region_fcoord_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_region_fcoord_RLAST : in STD_LOGIC;
    m_axi_my_region_fcoord_RVALID : in STD_LOGIC;
    m_axi_my_region_fcoord_RREADY : out STD_LOGIC;
    m_axi_my_patches_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_patches_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_patches_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_patches_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_patches_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_AWVALID : out STD_LOGIC;
    m_axi_my_patches_AWREADY : in STD_LOGIC;
    m_axi_my_patches_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_patches_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_WLAST : out STD_LOGIC;
    m_axi_my_patches_WVALID : out STD_LOGIC;
    m_axi_my_patches_WREADY : in STD_LOGIC;
    m_axi_my_patches_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_BVALID : in STD_LOGIC;
    m_axi_my_patches_BREADY : out STD_LOGIC;
    m_axi_my_patches_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_patches_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_patches_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_patches_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_patches_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_patches_ARVALID : out STD_LOGIC;
    m_axi_my_patches_ARREADY : in STD_LOGIC;
    m_axi_my_patches_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_patches_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_patches_RLAST : in STD_LOGIC;
    m_axi_my_patches_RVALID : in STD_LOGIC;
    m_axi_my_patches_RREADY : out STD_LOGIC;
    m_axi_my_pos_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_pos_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_pos_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_pos_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_pos_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_AWVALID : out STD_LOGIC;
    m_axi_my_pos_AWREADY : in STD_LOGIC;
    m_axi_my_pos_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_pos_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_WLAST : out STD_LOGIC;
    m_axi_my_pos_WVALID : out STD_LOGIC;
    m_axi_my_pos_WREADY : in STD_LOGIC;
    m_axi_my_pos_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_BVALID : in STD_LOGIC;
    m_axi_my_pos_BREADY : out STD_LOGIC;
    m_axi_my_pos_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_pos_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_pos_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_pos_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_pos_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_pos_ARVALID : out STD_LOGIC;
    m_axi_my_pos_ARREADY : in STD_LOGIC;
    m_axi_my_pos_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_pos_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_pos_RLAST : in STD_LOGIC;
    m_axi_my_pos_RVALID : in STD_LOGIC;
    m_axi_my_pos_RREADY : out STD_LOGIC;
    m_axi_my_debug_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_debug_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_AWVALID : out STD_LOGIC;
    m_axi_my_debug_AWREADY : in STD_LOGIC;
    m_axi_my_debug_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_WLAST : out STD_LOGIC;
    m_axi_my_debug_WVALID : out STD_LOGIC;
    m_axi_my_debug_WREADY : in STD_LOGIC;
    m_axi_my_debug_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_BVALID : in STD_LOGIC;
    m_axi_my_debug_BREADY : out STD_LOGIC;
    m_axi_my_debug_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_debug_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_ARVALID : out STD_LOGIC;
    m_axi_my_debug_ARREADY : in STD_LOGIC;
    m_axi_my_debug_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_RLAST : in STD_LOGIC;
    m_axi_my_debug_RVALID : in STD_LOGIC;
    m_axi_my_debug_RREADY : out STD_LOGIC;
    m_axi_my_debug_array_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_array_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_debug_array_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_array_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_array_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_AWVALID : out STD_LOGIC;
    m_axi_my_debug_array_AWREADY : in STD_LOGIC;
    m_axi_my_debug_array_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_array_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_WLAST : out STD_LOGIC;
    m_axi_my_debug_array_WVALID : out STD_LOGIC;
    m_axi_my_debug_array_WREADY : in STD_LOGIC;
    m_axi_my_debug_array_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_BVALID : in STD_LOGIC;
    m_axi_my_debug_array_BREADY : out STD_LOGIC;
    m_axi_my_debug_array_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_array_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_my_debug_array_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_array_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_my_debug_array_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_my_debug_array_ARVALID : out STD_LOGIC;
    m_axi_my_debug_array_ARREADY : in STD_LOGIC;
    m_axi_my_debug_array_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_my_debug_array_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_my_debug_array_RLAST : in STD_LOGIC;
    m_axi_my_debug_array_RVALID : in STD_LOGIC;
    m_axi_my_debug_array_RREADY : out STD_LOGIC
  );

end design_1_batch_align2D_region_0_1;

architecture stub of design_1_batch_align2D_region_0_1 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_ctrl_AWADDR[5:0],s_axi_ctrl_AWVALID,s_axi_ctrl_AWREADY,s_axi_ctrl_WDATA[31:0],s_axi_ctrl_WSTRB[3:0],s_axi_ctrl_WVALID,s_axi_ctrl_WREADY,s_axi_ctrl_BRESP[1:0],s_axi_ctrl_BVALID,s_axi_ctrl_BREADY,s_axi_ctrl_ARADDR[5:0],s_axi_ctrl_ARVALID,s_axi_ctrl_ARREADY,s_axi_ctrl_RDATA[31:0],s_axi_ctrl_RRESP[1:0],s_axi_ctrl_RVALID,s_axi_ctrl_RREADY,s_axi_param_AWADDR[5:0],s_axi_param_AWVALID,s_axi_param_AWREADY,s_axi_param_WDATA[31:0],s_axi_param_WSTRB[3:0],s_axi_param_WVALID,s_axi_param_WREADY,s_axi_param_BRESP[1:0],s_axi_param_BVALID,s_axi_param_BREADY,s_axi_param_ARADDR[5:0],s_axi_param_ARVALID,s_axi_param_ARREADY,s_axi_param_RDATA[31:0],s_axi_param_RRESP[1:0],s_axi_param_RVALID,s_axi_param_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_my_region_data_AWADDR[31:0],m_axi_my_region_data_AWLEN[7:0],m_axi_my_region_data_AWSIZE[2:0],m_axi_my_region_data_AWBURST[1:0],m_axi_my_region_data_AWLOCK[1:0],m_axi_my_region_data_AWREGION[3:0],m_axi_my_region_data_AWCACHE[3:0],m_axi_my_region_data_AWPROT[2:0],m_axi_my_region_data_AWQOS[3:0],m_axi_my_region_data_AWVALID,m_axi_my_region_data_AWREADY,m_axi_my_region_data_WDATA[31:0],m_axi_my_region_data_WSTRB[3:0],m_axi_my_region_data_WLAST,m_axi_my_region_data_WVALID,m_axi_my_region_data_WREADY,m_axi_my_region_data_BRESP[1:0],m_axi_my_region_data_BVALID,m_axi_my_region_data_BREADY,m_axi_my_region_data_ARADDR[31:0],m_axi_my_region_data_ARLEN[7:0],m_axi_my_region_data_ARSIZE[2:0],m_axi_my_region_data_ARBURST[1:0],m_axi_my_region_data_ARLOCK[1:0],m_axi_my_region_data_ARREGION[3:0],m_axi_my_region_data_ARCACHE[3:0],m_axi_my_region_data_ARPROT[2:0],m_axi_my_region_data_ARQOS[3:0],m_axi_my_region_data_ARVALID,m_axi_my_region_data_ARREADY,m_axi_my_region_data_RDATA[31:0],m_axi_my_region_data_RRESP[1:0],m_axi_my_region_data_RLAST,m_axi_my_region_data_RVALID,m_axi_my_region_data_RREADY,m_axi_my_region_fcoord_AWADDR[31:0],m_axi_my_region_fcoord_AWLEN[7:0],m_axi_my_region_fcoord_AWSIZE[2:0],m_axi_my_region_fcoord_AWBURST[1:0],m_axi_my_region_fcoord_AWLOCK[1:0],m_axi_my_region_fcoord_AWREGION[3:0],m_axi_my_region_fcoord_AWCACHE[3:0],m_axi_my_region_fcoord_AWPROT[2:0],m_axi_my_region_fcoord_AWQOS[3:0],m_axi_my_region_fcoord_AWVALID,m_axi_my_region_fcoord_AWREADY,m_axi_my_region_fcoord_WDATA[31:0],m_axi_my_region_fcoord_WSTRB[3:0],m_axi_my_region_fcoord_WLAST,m_axi_my_region_fcoord_WVALID,m_axi_my_region_fcoord_WREADY,m_axi_my_region_fcoord_BRESP[1:0],m_axi_my_region_fcoord_BVALID,m_axi_my_region_fcoord_BREADY,m_axi_my_region_fcoord_ARADDR[31:0],m_axi_my_region_fcoord_ARLEN[7:0],m_axi_my_region_fcoord_ARSIZE[2:0],m_axi_my_region_fcoord_ARBURST[1:0],m_axi_my_region_fcoord_ARLOCK[1:0],m_axi_my_region_fcoord_ARREGION[3:0],m_axi_my_region_fcoord_ARCACHE[3:0],m_axi_my_region_fcoord_ARPROT[2:0],m_axi_my_region_fcoord_ARQOS[3:0],m_axi_my_region_fcoord_ARVALID,m_axi_my_region_fcoord_ARREADY,m_axi_my_region_fcoord_RDATA[31:0],m_axi_my_region_fcoord_RRESP[1:0],m_axi_my_region_fcoord_RLAST,m_axi_my_region_fcoord_RVALID,m_axi_my_region_fcoord_RREADY,m_axi_my_patches_AWADDR[31:0],m_axi_my_patches_AWLEN[7:0],m_axi_my_patches_AWSIZE[2:0],m_axi_my_patches_AWBURST[1:0],m_axi_my_patches_AWLOCK[1:0],m_axi_my_patches_AWREGION[3:0],m_axi_my_patches_AWCACHE[3:0],m_axi_my_patches_AWPROT[2:0],m_axi_my_patches_AWQOS[3:0],m_axi_my_patches_AWVALID,m_axi_my_patches_AWREADY,m_axi_my_patches_WDATA[31:0],m_axi_my_patches_WSTRB[3:0],m_axi_my_patches_WLAST,m_axi_my_patches_WVALID,m_axi_my_patches_WREADY,m_axi_my_patches_BRESP[1:0],m_axi_my_patches_BVALID,m_axi_my_patches_BREADY,m_axi_my_patches_ARADDR[31:0],m_axi_my_patches_ARLEN[7:0],m_axi_my_patches_ARSIZE[2:0],m_axi_my_patches_ARBURST[1:0],m_axi_my_patches_ARLOCK[1:0],m_axi_my_patches_ARREGION[3:0],m_axi_my_patches_ARCACHE[3:0],m_axi_my_patches_ARPROT[2:0],m_axi_my_patches_ARQOS[3:0],m_axi_my_patches_ARVALID,m_axi_my_patches_ARREADY,m_axi_my_patches_RDATA[31:0],m_axi_my_patches_RRESP[1:0],m_axi_my_patches_RLAST,m_axi_my_patches_RVALID,m_axi_my_patches_RREADY,m_axi_my_pos_AWADDR[31:0],m_axi_my_pos_AWLEN[7:0],m_axi_my_pos_AWSIZE[2:0],m_axi_my_pos_AWBURST[1:0],m_axi_my_pos_AWLOCK[1:0],m_axi_my_pos_AWREGION[3:0],m_axi_my_pos_AWCACHE[3:0],m_axi_my_pos_AWPROT[2:0],m_axi_my_pos_AWQOS[3:0],m_axi_my_pos_AWVALID,m_axi_my_pos_AWREADY,m_axi_my_pos_WDATA[31:0],m_axi_my_pos_WSTRB[3:0],m_axi_my_pos_WLAST,m_axi_my_pos_WVALID,m_axi_my_pos_WREADY,m_axi_my_pos_BRESP[1:0],m_axi_my_pos_BVALID,m_axi_my_pos_BREADY,m_axi_my_pos_ARADDR[31:0],m_axi_my_pos_ARLEN[7:0],m_axi_my_pos_ARSIZE[2:0],m_axi_my_pos_ARBURST[1:0],m_axi_my_pos_ARLOCK[1:0],m_axi_my_pos_ARREGION[3:0],m_axi_my_pos_ARCACHE[3:0],m_axi_my_pos_ARPROT[2:0],m_axi_my_pos_ARQOS[3:0],m_axi_my_pos_ARVALID,m_axi_my_pos_ARREADY,m_axi_my_pos_RDATA[31:0],m_axi_my_pos_RRESP[1:0],m_axi_my_pos_RLAST,m_axi_my_pos_RVALID,m_axi_my_pos_RREADY,m_axi_my_debug_AWADDR[31:0],m_axi_my_debug_AWLEN[7:0],m_axi_my_debug_AWSIZE[2:0],m_axi_my_debug_AWBURST[1:0],m_axi_my_debug_AWLOCK[1:0],m_axi_my_debug_AWREGION[3:0],m_axi_my_debug_AWCACHE[3:0],m_axi_my_debug_AWPROT[2:0],m_axi_my_debug_AWQOS[3:0],m_axi_my_debug_AWVALID,m_axi_my_debug_AWREADY,m_axi_my_debug_WDATA[31:0],m_axi_my_debug_WSTRB[3:0],m_axi_my_debug_WLAST,m_axi_my_debug_WVALID,m_axi_my_debug_WREADY,m_axi_my_debug_BRESP[1:0],m_axi_my_debug_BVALID,m_axi_my_debug_BREADY,m_axi_my_debug_ARADDR[31:0],m_axi_my_debug_ARLEN[7:0],m_axi_my_debug_ARSIZE[2:0],m_axi_my_debug_ARBURST[1:0],m_axi_my_debug_ARLOCK[1:0],m_axi_my_debug_ARREGION[3:0],m_axi_my_debug_ARCACHE[3:0],m_axi_my_debug_ARPROT[2:0],m_axi_my_debug_ARQOS[3:0],m_axi_my_debug_ARVALID,m_axi_my_debug_ARREADY,m_axi_my_debug_RDATA[31:0],m_axi_my_debug_RRESP[1:0],m_axi_my_debug_RLAST,m_axi_my_debug_RVALID,m_axi_my_debug_RREADY,m_axi_my_debug_array_AWADDR[31:0],m_axi_my_debug_array_AWLEN[7:0],m_axi_my_debug_array_AWSIZE[2:0],m_axi_my_debug_array_AWBURST[1:0],m_axi_my_debug_array_AWLOCK[1:0],m_axi_my_debug_array_AWREGION[3:0],m_axi_my_debug_array_AWCACHE[3:0],m_axi_my_debug_array_AWPROT[2:0],m_axi_my_debug_array_AWQOS[3:0],m_axi_my_debug_array_AWVALID,m_axi_my_debug_array_AWREADY,m_axi_my_debug_array_WDATA[31:0],m_axi_my_debug_array_WSTRB[3:0],m_axi_my_debug_array_WLAST,m_axi_my_debug_array_WVALID,m_axi_my_debug_array_WREADY,m_axi_my_debug_array_BRESP[1:0],m_axi_my_debug_array_BVALID,m_axi_my_debug_array_BREADY,m_axi_my_debug_array_ARADDR[31:0],m_axi_my_debug_array_ARLEN[7:0],m_axi_my_debug_array_ARSIZE[2:0],m_axi_my_debug_array_ARBURST[1:0],m_axi_my_debug_array_ARLOCK[1:0],m_axi_my_debug_array_ARREGION[3:0],m_axi_my_debug_array_ARCACHE[3:0],m_axi_my_debug_array_ARPROT[2:0],m_axi_my_debug_array_ARQOS[3:0],m_axi_my_debug_array_ARVALID,m_axi_my_debug_array_ARREADY,m_axi_my_debug_array_RDATA[31:0],m_axi_my_debug_array_RRESP[1:0],m_axi_my_debug_array_RLAST,m_axi_my_debug_array_RVALID,m_axi_my_debug_array_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "batch_align2D_region,Vivado 2018.3";
begin
end;
