webtalk_init -webtalk_dir /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-16 14:59:24" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210887764_1777536713_210696317_641" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "oj0poj3432emk0t8u8dgacp203" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.6.1810 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.909 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1571230613000" -context "sdk\\\\bsp/1571230613000"
webtalk_add_data -client sdk -key hwid -value "1571230379000" -context "sdk\\\\bsp/1571230613000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1571230613000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1571230613000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1571230613000"
webtalk_add_data -client sdk -key uid -value "1571230617000" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key hwid -value "1571230379000" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key bspid -value "1571230613000" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1571230617000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1571230764001"
webtalk_transmit -clientid 2087347022 -regid "210887764_1777536713_210696317_641" -xml /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
