# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/davide/FPGA-design/svo_align2d_design/svo_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_9/design_1_batch_align2D_0_9.xci
# IP: The module: 'design_1_batch_align2D_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/davide/FPGA-design/svo_align2d_design/svo_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_9/constraints/batch_align2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_batch_align2D_0_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/davide/FPGA-design/svo_align2d_design/svo_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_9/design_1_batch_align2D_0_9.xci
# IP: The module: 'design_1_batch_align2D_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/davide/FPGA-design/svo_align2d_design/svo_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_9/constraints/batch_align2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_batch_align2D_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
