# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_0/design_1_batch_align2D_0_0.xci
# IP: The module: 'design_1_batch_align2D_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_0/constraints/batch_align2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_batch_align2D_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_0/design_1_batch_align2D_0_0.xci
# IP: The module: 'design_1_batch_align2D_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_batch_align2D_0_0/constraints/batch_align2D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_batch_align2D_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
