#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jan 06 18:37:08 CET 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_4 zynq_ultra_ps_e_vip_v1_0_4 xbip_utils_v3_0_9 axi_utils_v2_0_5 xbip_pipe_v3_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_dsp48_multadd_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 floating_point_v7_1_7 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_18 fifo_generator_v13_2_3 axi_data_fifo_v2_1_17 axi_crossbar_v2_1_19 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlconstant_v1_1_5 smartconnect_v1_0 axi_protocol_converter_v2_1_18 axi_clock_converter_v2_1_17 blk_mem_gen_v8_4_2 axi_dwidth_converter_v2_1_18)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/cad/xilinx/Vivado/2018.3/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "/cad/xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/cad/xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/cad/xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/cad/xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/98af/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim/design_1_zynq_ultra_ps_e_0_1_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_7 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/c63e/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_ctrl_s_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_dcmp_64ns_64ns_1_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_dmul_64ns_64ns_64_8_max_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_dsub_64ns_64ns_64_8_full_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fadd_32ns_32ns_32_7_full_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_faddfsub_32ns_32ns_32_7_full_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fdiv_32ns_32ns_32_12_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fmul_32ns_32ns_32_4_max_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fpext_32ns_64_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fptrunc_64ns_32_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_fsub_32ns_32ns_32_5_no_dsp_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_mux_32_32_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_mux_94_32_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_mux_164_8_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_mux_646_32_1_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_my_patches_m_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_my_pos_m_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_my_region_data_m_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_my_region_fcoord_m_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_param_s_axi.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_pyr_region_data_0.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_ref_patch_with_borde_15.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_sitofp_32ns_32_6_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region_sitofp_32s_32_6_1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/gauss_newton_optim_r.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/gauss_newton_optim_r_mask_table1.v" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/verilog/batch_align2D_region.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_dcmp_0_no_dsp_64.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_dmul_6_max_dsp_64.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_dsub_6_full_dsp_64.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fadd_5_full_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_faddfsub_5_full_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fdiv_10_no_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fptrunc_0_no_dsp_64.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_fsub_3_no_dsp_32.vhd" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/61fd/hdl/ip/batch_align2D_region_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_batch_align2D_region_0_1/sim/design_1_batch_align2D_region_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/64f4/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_3 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_96M_0/sim/design_1_rst_ps8_0_96M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/9ade/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_s02mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_s02tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_48ac_s02sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_48ac_s02a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_48ac_sarn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_48ac_srn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_48ac_sawn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_48ac_swn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_48ac_sbn_2.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_48ac_s03mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_48ac_s03tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_48ac_s03sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_48ac_s03a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_48ac_sarn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_48ac_srn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_48ac_sawn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_48ac_swn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/sim/bd_48ac_sbn_3.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/sim/bd_48ac_s04mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/sim/bd_48ac_s04tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/sim/bd_48ac_s04sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/sim/bd_48ac_s04a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/sim/bd_48ac_sarn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/sim/bd_48ac_srn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/sim/bd_48ac_sawn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_50/sim/bd_48ac_swn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/sim/bd_48ac_sbn_4.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/sim/bd_48ac_s05mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/sim/bd_48ac_s05tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/sim/bd_48ac_s05sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/sim/bd_48ac_s05a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/sim/bd_48ac_sarn_5.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_57/sim/bd_48ac_srn_5.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/sim/bd_48ac_sawn_5.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/sim/bd_48ac_swn_5.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/sim/bd_48ac_sbn_5.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/sim/bd_48ac_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/sim/bd_48ac_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/sim/bd_48ac_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_64/sim/bd_48ac_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/sim/bd_48ac_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/sim/bd_48ac_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/sim/bd_48ac_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/693a/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/37c2/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/0815/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/00a3/hdl" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim_tlm" +incdir+"$ref_dir/../../../../batch_align2d_design.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1" +incdir+"/cad/xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/dmalvezzi/batch_align2d/design/batch_align2d_design/batch_align2d_design.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
