// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_hls_fptoui_float_i (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [31:0] x;
output  [7:0] ap_return;

wire   [31:0] p_Val2_s_fu_38_p1;
wire   [22:0] tmp_V_37_fu_52_p1;
wire   [24:0] mantissa_V_fu_56_p4;
wire   [7:0] tmp_V_fu_42_p4;
wire   [8:0] tmp_i_i_i_cast1_fu_70_p1;
wire   [8:0] sh_assign_fu_74_p2;
wire   [7:0] tmp_i_i_fu_88_p2;
wire   [0:0] isNeg_fu_80_p3;
wire  signed [8:0] tmp_i_i_cast_fu_94_p1;
wire  signed [8:0] ush_fu_98_p3;
wire  signed [31:0] sh_assign_2_cast_fu_106_p1;
wire  signed [24:0] sh_assign_2_cast_cas_fu_110_p1;
wire   [54:0] mantissa_V_1_cast2_fu_66_p1;
wire   [54:0] tmp_i_i_1181_fu_114_p1;
wire   [24:0] r_V_fu_118_p2;
wire   [0:0] tmp_1505_fu_130_p3;
wire   [54:0] r_V_1_fu_124_p2;
wire   [7:0] tmp_fu_138_p1;
wire   [7:0] tmp_s_fu_142_p4;

assign ap_ready = 1'b1;

assign ap_return = ((isNeg_fu_80_p3[0:0] === 1'b1) ? tmp_fu_138_p1 : tmp_s_fu_142_p4);

assign isNeg_fu_80_p3 = sh_assign_fu_74_p2[32'd8];

assign mantissa_V_1_cast2_fu_66_p1 = mantissa_V_fu_56_p4;

assign mantissa_V_fu_56_p4 = {{{{1'd1}, {tmp_V_37_fu_52_p1}}}, {1'd0}};

assign p_Val2_s_fu_38_p1 = x;

assign r_V_1_fu_124_p2 = mantissa_V_1_cast2_fu_66_p1 << tmp_i_i_1181_fu_114_p1;

assign r_V_fu_118_p2 = mantissa_V_fu_56_p4 >> sh_assign_2_cast_cas_fu_110_p1;

assign sh_assign_2_cast_cas_fu_110_p1 = ush_fu_98_p3;

assign sh_assign_2_cast_fu_106_p1 = ush_fu_98_p3;

assign sh_assign_fu_74_p2 = ($signed(9'd385) + $signed(tmp_i_i_i_cast1_fu_70_p1));

assign tmp_1505_fu_130_p3 = r_V_fu_118_p2[32'd24];

assign tmp_V_37_fu_52_p1 = p_Val2_s_fu_38_p1[22:0];

assign tmp_V_fu_42_p4 = {{p_Val2_s_fu_38_p1[30:23]}};

assign tmp_fu_138_p1 = tmp_1505_fu_130_p3;

assign tmp_i_i_1181_fu_114_p1 = $unsigned(sh_assign_2_cast_fu_106_p1);

assign tmp_i_i_cast_fu_94_p1 = $signed(tmp_i_i_fu_88_p2);

assign tmp_i_i_fu_88_p2 = (8'd127 - tmp_V_fu_42_p4);

assign tmp_i_i_i_cast1_fu_70_p1 = tmp_V_fu_42_p4;

assign tmp_s_fu_142_p4 = {{r_V_1_fu_124_p2[31:24]}};

assign ush_fu_98_p3 = ((isNeg_fu_80_p3[0:0] === 1'b1) ? tmp_i_i_cast_fu_94_p1 : sh_assign_fu_74_p2);

endmodule //p_hls_fptoui_float_i
